# Welcome to Jekyll!
#
# Toto je soubor s hlavním nastavením. Na začátku je nastavení proměných, které
# je třeba přispůsobit si pro váš web. Později v anglicky popsané části jsou více
# technické nastavení
#

title: Piráti - Most
email: ustecko@pirati.cz
description: Prosazujeme fungující moderní politiku založenou na využití technologií 21. století pro otevřenou demokratickou společnost.
keywords: piráti, česká pirátská strana, svoboda, demokracie, název města, zkratka města, místní združení,
url: "https://ustecky.pirati.cz" # the base hostname & protocol for your site, e.g. http://example.com

administrator:
  email: vaclav.zidek@pirati.cz # mail kam pujdou chybove vystupy

theme: jekyll-theme-pirati

sass:
  style: compressed
  sass_dir: _sass

organization:
  name: Česka pirátská strana - Most
  shortName: Piráti - Most
  email: adam.komenda@pirati.cz
  phone: +420 731 698 142
  address: |
    Pařížská 1290/5
    400 01 Ústí nad Labem
  residenceImg: Supice01.jpg
  mapLink: https://www.google.cz/maps/place/SUPICE/@50.6612183,14.0344671,18.5z/data=!4m5!3m4!1s0x4709850183d101b7:0x9b56460616ed3188!8m2!3d50.6612787!4d14.0352704
  redmineLink: https://redmine.pirati.cz/projects

homepageBanner:
  display: false
  link: /komunalni-volby/
  title: Komunální volby 2018
  breakpoint: 640 # breakpoint in pixels when to start showing `default` instead of `mobile`
  image:
    default: path/to/img.jpg
    mobile: path/to/img.jpg

calendar:
  # Get api key from Google Developer Console
  apiKey: AIzaSyAXWWBxhDChm00CQv_BeK-WI_VuebYr9a8
  title: Pirátský kalendář
  id: uskpirati@gmail.com
  page: https://calendar.google.com/calendar/embed?showTitle=0&amp;showNav=0&amp;showDate=0&amp;showPrint=0&amp;showTabs=0&amp;showCalendars=0&amp;showTz=0&amp;mode=AGENDA&amp;height=500&amp;wkst=2&amp;hl=cs&amp;bgcolor=%23FFFFFF&amp;src=uskpirati%40gmail.com&ctz=Europe%2FPrague&amp;color=%232952A3


facebook:
  loadSDK: true
  profilePage:
  appId: 496346277123749

twitter:
  loadSDK: true
  profile: PiratskaStrana

instagram:
  profilePage: https://www.instagram.com/pirati.cz/

gplus:
  profilePage: https://plus.google.com/u/0/+piratskastrana

flicker:
  profilePage: https://www.flickr.com/photos/pirati/

forum:
  page: https://forum.pirati.cz/

github:
  url: https://github.com/pirati-web/ustecky.pirati.cz/
  branch: master



# Build settings
markdown: kramdown
theme: jekyll-theme-pirati
plugins:
  - jekyll-feed
  - jekyll-paginate
  - jekyll-sitemap
paginate_path: "/aktuality/:num/"
paginate: 11

exclude:
  - Dockerfile
  - docker-compose.yml
  - deploy_rsa_sandbox.enc
  - deploy_rsa_sandbox.pub
  - navod.md
  - readme.md
  - Gemfile
  - Gemfile.lock
  - vendor

permalink: /aktuality/:title.html
collections:
  people:
    output: true
    permalink: /lide/:path/
  program:
    output: true
    permalink: /program/:path/

defaults:   # defaults values for collection scope
  -
    scope:
      path: "_people"
    values:
      layout: "page"
      rbar: "foto"
  -
    scope:
      path: "_program"
    values:
      layout: "page"
      rbar: "garant, program"

emptyArray: []

assets:
  source_maps: true
  compression: true
  gzip: false
  plugins:
    css: { autoprefixer: {}}
    img:
      optim:
        jpegoptim:
          strip: all
          max_quality: 80
  autoprefixer:
    browsers:
      - "last 2 versions"
      - "IE > 9"
  sources:
    - vendor/bundle/ruby/2.5.0/gems/jekyll-theme-pirati-7.5.0/_sass
    - assets/css
    - assets/fonts
    - assets/video
    - assets/img
    - assets/img/posts
    - _sass
